import torch.nn as nn
from .embeddings import TransformerEmbeddings
from .model import Encoder, Decoder

class Transformer(nn.Module): 
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model, n_layers, n_heads, d_ff, dropout, max_seq_len):
        super().__init__()

        # Embeddings from embeddings.py, one for each of src_seq and tgt_seq 
        self.src_embed = TransformerEmbeddings(src_vocab_size, d_model, max_seq_len, dropout)
        self.tgt_embed = TransformerEmbeddings(tgt_vocab_size, d_model, max_seq_len, dropout)
    
        # Encoder and Decoder stacks 
        self.encoder = Encoder(d_model, n_layers, n_heads, d_ff, dropout)
        self.decoder = Decoder(d_model, n_layers, n_heads, d_ff, dropout)

        # the final projection for probabilities 
        self.generator = nn.Linear(d_model, tgt_vocab_size)


    def forward(self, src, tgt, src_mask, tgt_mask): 
        """
            src: (batch_size, src_seq_len)
            tgt: (batch_size, tgt_seq_len)
            src_mask: (batch_size, 1, 1, src_seq_len)
            tgt_mask: (batch_size, 1, tgt_seq_len, tgt_seq_len)
        """

        # run the src through the Encoder 
        memory = self.encoder(self.src_embed(src), src_mask) # (batch_size, src_seq_len, d_model)

        # run the target through the Decoder, it uses the memory generated by the Encoder 
        output = self.decoder(self.tgt_embed(tgt), memory, src_mask, tgt_mask) # (batch_size, tgt_seq_len, d_model)

        # final projection for probability 
        output = self.generator(output) # (batch_size, tgt_seq_len, tgt_vocab_size)
        return output